<script src="{{asset('assets/js/jquery.min.js')}}"></script>
<script src="{{asset('assets/js/popper.min.js')}}"></script>
<script src="{{asset('assets/js/bootstrap.min.js')}}"></script>
<script src="{{asset('assets/js/app.common.min.js')}}"></script>
<script src="{{asset('assets/js/Chart.min.js') }}"></script>
<script src="{{asset('assets/js/moment.min.js')}}"></script>
<script src="{{asset('assets/js/daterangepicker.min.js')}}"></script>
<script src="{{asset('assets/js/app.referral.dashboard.min.js') }}"></script>
<script src="{{asset('assets/js/jquery.dataTables.min.js')}}"></script>
<script src="https://cdn.datatables.net/1.10.22/js/dataTables.bootstrap4.min.js"></script>
<!--<script src="../assets/js/app.referral.vbc.min.js"></script>-->
<script src="{{asset('assets/js/jquery.custom-file-input.js')}}"></script>
<script src="{{asset('assets/js/app.referral.vbc.upload.bulk.data.min.js')}}"></script>