<?php

return [

    'labResult' => [
        'positive' => 'Positive',
        'negative' => 'Negative'
    ],

    'labImmunizationResult' => [
        'immune' => 'Immune',
        'non_immune' => 'Non Immune'
    ],

    'employeePhysicalResult' => [
        'completed' => 'Completed',
        'overdue' => 'Overdue'
    ],

    'status' => [
        '1' => 'Active',
        '0' => 'InActive',
    ],
    
    'userStatus' => [
        // '0' => 'Pending',
        '1' => 'Active',
        '2' => 'InActive',
        '3' => 'Reject',
        // '4' => 'Initial',
        '5' => 'Completed'
    ],

    'gender' => [
        '1' => 'Male',
        '2' => 'Female',
        '3' => 'Other',
    ],

    'ethnicity' => [
        'Hispanic or Latino' => 'Hispanic or Latino',
        'Not Hispanic or Latino' => 'Not Hispanic or Latino',
    ],

    'services' => [
        '1' => 'VBC',
        '2' => 'MD Order',
        '3' => 'Occupational Health',
    ],

    'designation' => [
        'admin' => 'Admin',
        'supervisior' => 'Supervisior',
        'coordinator' => 'Coordinator',
        'fieldvisitor' => 'Field Visitor',
    ],

    'address_type' => [
        'GPS' => 'GPS',
        'Home' => 'Home',
        'Community' => 'Community',
    ],

    'relations' => [
        'father' => 'Father',
        'mother' => 'Mother',
        'parent' => 'Parent',
        'son' => 'Son',
        'daughter' => 'Daughter',
        'child' => 'Child',
        'husband' => 'Husband',
        'wife' => 'Wife',
        'spouse' => 'Spouse',
        'brother' => 'Brother',
        'sister' => 'Sister',
        'sibling' => 'Sibling',
        'uncle' => 'Uncle',
        'aunt' => 'Aunt',
        'step mother' => 'Step Mother',
        'nephew' => 'Nephew',
        'cousin' => 'Cousin',
        'step mother' => 'Step Daughter In Law',
        'son in law' => 'Son In Law',
        'sister in law' => 'Sister In Law'
    ],

    'language' => [
        'African' => 'African',
        'Albanian' => 'Albanian',
        'American Sign Language' => 'American Sign Language',
        'Amharic' => 'Amharic',
        'Arabic' => 'Arabic',
        'Armenian' => 'Armenian',
        'Ashanti' => 'Ashanti',
        'Azerbaijani' => 'Azerbaijani',
        'Belarusian' => 'Belarusian',
        'Bengali' => 'Bengali',
        'Bilingual' => 'Bilingual',
        'Bosnian' => 'Bosnian',
        'Bulgaria' => 'Bulgaria',
        'Burmese' => 'Burmese',
        'Cantonese' => 'Cantonese',
        'Chinese'=>  'Chinese',
        'Creole' => 'Creole',
        'Croatian' => 'Croatian',
        'Czech' => 'Czech',
        'Danish' => 'Danish',
        'Dari' => 'Dari',
        'Dutch' => 'Dutch',
        'Edo/Bini' => 'Edo/Bini',
        'English'=>  'English',
        'Estonian' => 'Estonian',
        'Ethiopian' => 'Ethiopian',
        'Farsi' => 'Farsi',
        'Filipino' => 'Filipino',
        'French'=>  'French',
        'Fukkianese' => 'Fukkianese',
        'Fula/Fulani' => 'Fula/Fulani',
        'Fuzhounese' => 'Fuzhounese',
        'Georgian' => 'Georgian',
        'German' => 'German',
        'Ghana' => 'Ghana',
        'Greek' => 'Greek',
        'Gujarati' => 'Gujarati',
        'Guyanese' => 'Guyanese',
        'Haitian' => 'Haitian',
        'Hakka' => 'Hakka',
        'Hausa' => 'Hausa',
        'Hebrew'=>  'Hebrew',
        'Hindi' => 'Hindi',
        'Hungarian'=>  'Hungarian',
        'IGBO' => 'IGBO',
        'Indonesian' => 'Indonesian',
        'Italian' => 'Italian',
        'Jamaican' => 'Jamaican',
        'Japanese' => 'Japanese',
        'Kajainese' => 'Kajainese',
        'Kannada' => 'Kannada',
        'Kazakh' => 'Kazakh',
        'khmer' => 'khmer',
        'Khmer/Cambodian' => 'Khmer/Cambodian',
        'Kinyarwanda' => 'Kinyarwanda',
        'Korean' => 'Korean',
        'Krio' => 'Krio',
        'Kurdish' => 'Kurdish',
        'Kyrgyz' => 'Kyrgyz',
        'Lao' => 'Lao',
        'Latvian' => 'Latvian',
        'Lingala' => 'Lingala',
        'Lithuanian' => 'Lithuanian',
        'Malayalam' => 'Malayalam',
        'Mandarin' => 'Mandarin',
        'Nepali' => 'Nepali',
        'Pashto' => 'Pashto',
        'Patwa' => 'Patwa',
        'Persian' => 'Persian',
        'Polish' => 'Polish',
        'Portuguese' => 'Portuguese',
        'POTWARI' => 'POTWARI',
        'Punjabi' => 'Punjabi',
        'Romanian' => 'Romanian',
        'Russian'=>  'Russian',
        'Serbian' => 'Serbian',
        'Shanghainese' => 'Shanghainese',
        'Sinhala' => 'Sinhala',
        'Somali' => 'Somali',
        'Soninke' => 'Soninke',
        'Spanish'=>  'Spanish',
        'Swahili' => 'Swahili',
        'Tagalog' => 'Tagalog',
        'Taishan' => 'Taishan',
        'Taishanese' => 'Taishanese',
        'Taiwanese' => 'Taiwanese',
        'Tajik' => 'Tajik',
        'Temne' => 'Temne',
        'Thai' => 'Thai',
        'Tibetan' => 'Tibetan',
        'Turkish' => 'Turkish',
        'Twi' => 'Twi',
        'Ukrainian' => 'Ukrainian',
        'Urdu' => 'Urdu',
        'Uzbek' => 'Uzbek',
        'Vietnamese' => 'Vietnamese',
        'Wenzhounese' => 'Wenzhounese',
        'Yiddish'=>  'Yiddish',
        'Yoruba' => 'Yoruba',
        'Yugoslavia' => 'Yugoslavia',
    ],

    'race' => [
        'American Indian or Alaska Native' => 'American Indian or Alaska Native',
        'Asian' => 'Asian',
        'Black or African American' => 'Black or African American',
        'Native Hawaiian or Other Pacific Islander' => 'Native Hawaiian or Other Pacific Islander',
        'White' => 'White',
    ],
];